#!/bin/sh

# Copy last commit hash to clipboard on commit

echo "*************************************************************************************************************************************************"
echo "***************** OPEN PR : https://github.com/`git remote get-url origin | grep @ | sed -e 's/.*:\(.*\)/\1/'`/compare/"`git rev-parse --abbrev-ref HEAD`?expand=1
echo "*************************************************************************************************************************************************"
# Add other post-commit hooks 
